name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
      continue-on-error: true

    - name: Lint markdown files
      uses: nosborn/github-action-markdown-cli@v3.3.0
      with:
        files: .
        config_file: .markdownlint.json
      continue-on-error: true

  spell-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check spelling
      uses: rojopolis/spellcheck-github-actions@0.35.0
      with:
        config_path: .github/spellcheck-config.yml
      continue-on-error: true

  generate-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install documentation tools
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3 sphinx sphinx-rtd-theme

    - name: Generate API documentation
      run: |
        # This will generate docs when you have Python modules
        echo "Documentation generation placeholder"
      continue-on-error: true

    - name: Deploy documentation
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
      continue-on-error: true

